#!/usr/bin/env bash
# A script that configures a brand new Ubuntu machine to the requirements asked in this task.

sudo apt-get -y update
sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'

sudo echo "server {
        listen 80 default_server;
        listen [::]:80 default_server;
        add_header X-Served-By $HOSTNAME;
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name _;
        location / {
                try_files $uri $uri/ =404;
        }
	}" | sudo tee /etc/nginx/sites-available/default

sudo echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx start
