#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
sudo apt update
sudo apt install -y haproxy

cat <<EOF | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null
frontend http_front
    bind *:80
    mode http
    default_backend http_back

backend http_back
    mode http
    balance roundrobin
    server 112184-web-01 34.229.184.165:80 check
    server 112184-web-02 100.25.34.51:80 check
EOF

sudo systemctl enable haproxy
sudo systemctl restart haproxy
