#!/usr/bin/env bash
# displays the content of the file /etc/passwd

while IFS=":" read -a fields
do
    username=${fields[0]}
    userid=${fields[2]}
    homedir=${fields[5]}
    echo "Username: $username"
    echo "Username: $userid"
    echo "Home Directory: $homedir"
    echo ""
done < /etc/passwd
