#!/usr/bin/env bash

# Set IFS to ":" to split fields by ":"
IFS=":"

# Open /etc/passwd file for reading
while read -r -a fields
do
  USERNAME=${fields[0]}
  GROUP_ID=${fields[3]}
  HOME_DIRECTORY=${fields[5]}
  COMMAND_SHELL=${fields[6]}
  USER_ID=${fields[2]}
  PASSWORD=${fields[1]}
  USER_ID_INFO=${fields[4]}

  echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $HOME_DIRECTORY and rides $COMMAND_SHELL. $USER_ID's place is protected by the passcode $PASSWORD, more info about the user here: $USER_ID_INFO"
done < /etc/passwd
