#!/usr/bin/env bash
#  displays the visitor IP along with the HTTP status code from the Apache log file.
awk '{print $1" "$9}' < apache-access.log | sort -u | awk '{printf("IP:%s\tHTTP_CODE:%s ",$1,$2)}'
