#!/usr/bin/env bash
# groups visitors by IP and HTTP status code, and displays this data.
awk '{print $1" "$9}' < ./apache-access.log | sort -u | awk '{count[$1" "$2]++}END{for(i in count) printf("%d %s\t%s\n",count[i],i)}' | sort -nr
