#!/usr/bin/env bash
# task #1, make your fix short and sweet.
echo "user nginx nginx" > /etc/nginx/nginx.conf
port="8080"
ip=$(hostname -I | awk '{print $1}')
echo "listen $ip:$port" > /etc/nginx/conf.d/default.conf
sudo -u nginx service nginx start
